name: C++ Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with MSBuild
      run: |
        msbuild Step.sln /p:Configuration=Release /p:Platform=x64 /p:AdditionalOptions="/std:c++17"
